apiVersion: v2
name: project_manager
description: A Helm chart for my Kubernetes project
version: 0.1.0
dependencies:
  - name: prometheus
    version: "3.1.0"  # Replace with the desired version
    repository: "https://prometheus-community.github.io/helm-charts"
  - name: grafana
    version: "11.4.0"  # Replace with the desired version
    repository: "https://grafana.github.io/helm-charts"
  - name: loki
    version:"3.3.2"
    repository: "https://grafana.github.io/helm-charts"  



# Add and configure [Be clear what purposes you are on adding this Addons]


# [NOTE]
# ----------------------------------------------------------#
# ``````````````--https://landscape.cncf.io/--```````````````


# Add more helm repos here for different use cases
#    ___Networking plugins like Calico 
#    ___Traefik
#    ___Service Mesh like Istio 
#    ___Fluentd, Jaeger and others

#    ___And much more
#-----------------------------------------------------------#    