# Labels for various resources
labels:
  app: gemini
  environment: production

# Deployment settings
replicaCount: 2
image:
  repository: shakilkhan24/gemini_trial
  tag: latest
  pullPolicy: Always

# Service settings
service:
  type: NodePort
  port: 8501
  targetPort: 8501
  nodePort: 30001

# Resource limits
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

# Health checks
probes:
  initialDelay: 30
  period: 10

# Ingress settings
ingress:
  enabled: true
  host: geminiapp.com

# API Key
data:
  GOOGLE_API_KEY: "your-google-api-key-here"