apiVersion: v1
kind: ConfigMap
metadata:
  name: google-api-key-config
  labels:
    app: {{ .Values.labels.app }}
    environment: {{ .Values.labels.environment }}
    
data:
  GOOGLE_API_KEY: {{ .Values.data.GOOGLE_API_KEY }}
