apiVersion: apps/v1
kind: Deployment
metadata:
  name: gemini-deployment
  labels:
    app: {{ .Values.labels.app }}
    environment: {{ .Values.labels.environment }}
    
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
        environment: {{ .Values.labels.environment }}
    spec:
      containers:
        - name: gemini-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: GOOGLE_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: google-api-key-config
                  key: GOOGLE_API_KEY
