# DNS, TLS, HOST url setups, HTTP/HTTPS , IP , and others 
# I need to learn this before directly using Ingress


# .......Next.......
# apiVersion:
# kind: API GATEWAY 


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gemini-ingress
  labels:
    app: {{ .Values.labels.app }}
    environment: {{ .Values.labels.environment }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gemini-service
                port:
                  number: {{ .Values.service.port }}
