apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gemini-ingress
  labels:
    app: {{ .Values.labels.app }}
    environment: {{ .Values.labels.environment }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gemini-service
                port:
                  number: {{ .Values.service.port }}

# ________________________________________________________________#
# Think about to use ingress-nginx as api-gateway
# or kong , Istio , traefik or something ...