apiVersion: v1
kind: Service
metadata:
  name: gemini-service
  labels:
    app: gemini
spec:
  type: NodePort
  ports:
    - port: 8501
      targetPort: 8501
      nodePort: 30001  # Optional, Kubernetes will assign if omitted
  selector:
    app: gemini
